baseURL = "https://dineshsaravanan.com/"
languageCode = "en-us"
title = "Garden of Forking Thoughts"
theme = "hugo-theme-nix"
[params]
  Name = "Dinesh Saravanan Kumaraswamy"
  HeaderUsername = "blog"
  HeaderHostname = "dineshsaravanan.com"
  About = "Software Developer"
  ProfilePicture = "img/mugshot.jpg"
  Email = "dineshsaravanank@gmail.com"
  GithubID = "d-saravanan-kumaraswamy"
  RedditID = "dineshsaravanank"
  TwitterID = "dineshsaravanan"
